INSERT INTO publicaciones_inmobiliarias (
    localizacion_coordenadas,
    precio,
    concepto,
    barrio_o_ph,
    ph_o_especificacion,
    metros_cuadrados,
    metros_cuadrados_construidos,
    valor_m2,
    pisos,
    habitaciones,
    banos,
    parqueadero,
    antiguedad,
    descripcion,
    observacion,
    valor_administracion,
    link_1,
    link_2,
    link_3,
    imagenes,
    perfil_vendedor
)
VALUES (
    'Bogota, Colombia - 4.7110,-74.0721',
    450000000,
    'Venta apartamento',
    'Chapinero Alto',
    'Edificio Terraza Norte, apartamento exterior',
    82.50,
    78.00,
    5454545,
    1,
    3,
    2,
    TRUE,
    '5 a 10 anos',
    'Apartamento de prueba con sala comedor, cocina integral y buena iluminacion natural.',
    'Dato falso para pruebas locales del backend.',
    420000,
    'https://ejemplo.com/publicacion-prueba-1',
    'https://ejemplo.com/publicacion-prueba-1-detalle',
    'https://ejemplo.com/publicacion-prueba-1-contacto',
    ARRAY[
        'https://ejemplo.com/imagen1.jpg',
        'https://ejemplo.com/imagen2.jpg'
    ],
    'https://ejemplo.com/perfil-vendedor'
);
